DROP TABLE genres CASCADE;
DROP TABLE mpa_ratings CASCADE;
DROP TABLE films CASCADE;
DROP TABLE users CASCADE;
DROP TABLE user_friends CASCADE;
DROP TABLE film_likes CASCADE;
DROP TABLE film_genres CASCADE;
